using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

public enum Language
{
    Korean,
    English
}

// Minimal Korean/English string table. Deliberately not the Unity
// Localization package: the whole game has a few dozen strings, and this
// keeps it free of the Addressables dependency that package pulls in.
public static class Loc
{
    private const string PrefsKey = "language";

    public static event Action OnLanguageChanged;
    public static Language Current { get; private set; }

    static Loc()
    {
        var fallback = Application.systemLanguage == SystemLanguage.Korean ? Language.Korean : Language.English;
        Current = (Language)PlayerPrefs.GetInt(PrefsKey, (int)fallback);
    }

    public static void Set(Language language)
    {
        if (language == Current) return;
        Current = language;
        PlayerPrefs.SetInt(PrefsKey, (int)language);
        OnLanguageChanged?.Invoke();
    }

    public static string Get(string key)
    {
        if (!Table.TryGetValue(key, out var entry))
        {
            Debug.LogWarning($"Loc: missing string '{key}'");
            return key;
        }
        return Current == Language.Korean ? entry.ko : entry.en;
    }

    public static string Get(string key, params object[] args) => string.Format(Get(key), args);

    public static bool Has(string key) => Table.ContainsKey(key);

    // Every string in both languages, for the self check (SelfCheck).
    public static IEnumerable<(string key, string ko, string en)> Entries => Table.Select(kv => (kv.Key, kv.Value.ko, kv.Value.en));

    private static readonly Dictionary<string, (string ko, string en)> Table = new Dictionary<string, (string ko, string en)>
    {
        // Player 0 always owns the black stones and moves first (see GameScene).
        { "player.black", ("흑", "Black") },
        { "player.white", ("백", "White") },
        // The third and fourth sides of an online game of three or four.
        { "player.blue", ("청", "Blue") },
        { "player.red", ("적", "Red") },
        { "player.number", ("플레이어 {0}", "Player {0}") },
        // With janggi pieces the sides are Cho (moves first, like black) and Han.
        { "player.cho", ("초", "Cho") },
        { "player.han", ("한", "Han") },
        // The letters on janggi pieces, the same in both languages.
        { "piece.cho", ("초", "초") },
        { "piece.han", ("한", "한") },
        { "piece.cha", ("차", "차") },
        { "piece.po", ("포", "포") },
        { "piece.ma", ("마", "마") },
        { "piece.sang", ("상", "상") },
        { "piece.sa", ("사", "사") },
        { "piece.jol", ("졸", "졸") },
        { "piece.byeong", ("병", "병") },

        { "hud.turn", ("{0} 차례", "{0}'s turn") },
        { "hud.turnBadge", ("차례", "Turn") },
        { "hud.remaining", ("남은 알", "Pieces left") },
        { "hud.captured", ("잡은 알 {0}", "Captured {0}") },
        { "hud.turnTimed", ("{0} 차례 · {1}", "{0}'s turn · {1}") },
        { "hud.skip", ("턴 넘기기", "Skip turn") },
        { "hud.timeout", ("{0} 시간 초과 · 턴을 넘겨요", "{0} ran out of time") },
        { "hud.skipped", ("{0} 쪽이 턴을 넘겼어요", "{0} skipped the turn") },
        { "hud.menu", ("메뉴", "Menu") },
        { "hud.out.Knockout", ("탈락", "Out") },
        { "hud.out.Surrender", ("기권", "Conceded") },
        { "hud.out.OpponentLeft", ("나감", "Left") },
        { "hud.outNotice.Knockout", ("{0} 탈락", "{0} is out") },
        { "hud.outNotice.Surrender", ("{0} 쪽이 기권했어요", "{0} conceded") },
        { "hud.outNotice.OpponentLeft", ("{0} 쪽이 나갔어요", "{0} left") },
        { "hud.resetView", ("시점 초기화", "Reset view") },
        { "hud.fastForward", ("빨리 감기", "Fast forward") },
        { "hud.normalSpeed", ("보통 속도로", "Normal speed") },
        { "hud.hostFastForward", ("빨리 감는 중", "Fast-forwarding") },
        { "hud.start", ("대전 시작 · {0} 먼저", "Match start · {0} first") },
        { "hud.zoneWarn", ("이번 차례가 끝나면 가장자리가 무너져요", "The edge goes when this turn ends") },
        { "hud.zoneCrumbled", ("가장자리가 무너졌어요", "The edge crumbled") },
        { "hud.noPass", ("자기장 중에는 턴을 넘길 수 없어요", "No passing while the edge crumbles") },
        { "hud.zoneChip", ("자기장 {0}단계", "Edge · stage {0}") },
        { "hud.zoneChipWarn", ("자기장 곧 무너짐", "Edge · crumbling next") },
        { "hud.roundChip", ("라운드 {0}/{1}", "Round {0}/{1}") },
        { "hud.health", ("체력 {0}/{1}", "Health {0}/{1}") },
        { "kill.edge", ("자기장", "The edge") },
        { "kill.damage", ("-{0}", "-{0}") },
        { "reason.roundLimit", ("라운드 제한 · {0}이(가) 가장 많이 남았어요", "Round limit · {0} had the most left") },
        { "reason.roundLimitDraw", ("라운드 제한 · 남은 것이 같아 무승부예요", "Round limit · level, so a draw") },
        { "reason.healthOut", ("{0}의 체력이 모두 떨어졌어요", "{0} ran out of health") },
        { "stats.health", ("남은 체력", "Health left") },
        { "hint.flickKey", ("왼쪽 끌기", "Left drag") },
        { "hint.flick", ("당겼다 놓아 튕기기", "Pull back, release") },
        { "hint.CancelAim", ("조준 취소", "Cancel aim") },
        { "hint.FineAim", ("미세 조준 (누르는 동안)", "Fine aim (hold)") },
        { "hint.CameraView", ("시점 전환 (누르는 동안)", "Camera view (hold)") },
        { "hint.PanView", ("판 옮기기 (끌기)", "Pan the board (drag)") },
        { "hint.ResetView", ("시점 초기화", "Reset view") },
        { "hint.zoomKey", ("휠", "Wheel") },
        { "hint.zoom", ("확대·축소", "Zoom") },
        { "pause.title", ("메뉴", "Menu") },
        { "pause.resume", ("계속하기", "Resume") },
        { "pause.concede", ("기권", "Concede") },
        { "pause.concedeSide", ("{0} 기권", "{0} concedes") },
        { "pause.mainMenu", ("메인 메뉴로", "Main menu") },
        { "pause.confirm", ("한 번 더 누르면 확정", "Press again to confirm") },
        { "pause.captionLocal", ("Esc로 닫기 · 게임이 멈춰 있어요", "Esc closes · the game is paused") },
        { "pause.captionOnline", ("Esc로 닫기 · 온라인 대전은 멈추지 않아요", "Esc closes · online matches don't pause") },

        { "placement.title", ("알 배치", "Place pieces") },
        { "placement.hint", ("내 진영을 눌러 알을 놓으세요\n남은 알 {0}개", "Click inside your zone\n{0} left to place") },
        { "placement.hintMove", ("알을 끌어 옮길 수 있어요", "Drag a piece to move it") },
        { "placement.hintDone", ("모두 놓았어요", "All pieces placed") },
        { "placement.turn", ("{0} 배치 차례", "{0} to place") },
        { "placement.waiting", ("상대가 배치하는 중", "Opponent is placing") },
        { "placement.opponentReady", ("상대 준비 완료", "Opponent is ready") },
        { "placement.othersReady", ("{0}/{1}명 준비 완료", "{0}/{1} ready") },
        { "placement.readyDone", ("준비 완료 · 상대를 기다려요", "Ready · waiting for opponent") },
        { "placement.clock", ("{0} {1}", "{0} {1}") },
        { "placement.timeoutNote", ("시간이 끝나면 남은 알은 무작위로 놓여요", "Time up places the rest at random") },
        { "placement.ready", ("준비 완료", "Ready") },

        { "win.stamp", ("승", "Win") },
        { "win.title", ("{0} 승리", "{0} wins") },
        { "win.detail", ("{0} · 남은 돌 {1}개", "{0} · {1} stones left") },
        { "win.rematch", ("다시 하기", "Play again") },
        { "win.menu", ("메인 메뉴", "Main menu") },

        { "result.win", ("승리", "Victory") },
        { "result.lose", ("패배", "Defeat") },
        { "result.stampLose", ("패", "Loss") },
        { "reason.knockout", ("{0}의 알이 모두 떨어졌어요", "All of {0}'s pieces are off the board") },
        { "result.draw", ("무승부", "Draw") },
        { "result.stampDraw", ("무", "Draw") },
        { "reason.bothOut", ("마지막 알이 함께 떨어져 쏜 {0} 쪽이 졌어요", "Both last pieces went out, so {0} loses for shooting") },
        { "reason.bothOutWin", ("마지막 알이 함께 떨어져 쏜 {0} 쪽이 이겼어요", "Both last pieces went out, so {0} wins for shooting") },
        { "reason.surrender", ("{0} 쪽이 기권했어요", "{0} conceded") },
        { "reason.bothOutDraw", ("마지막 알이 함께 떨어져 무승부예요", "Both last pieces went out: a draw") },
        { "reason.opponentLeft", ("상대가 게임을 나갔어요", "Your opponent left the game") },
        { "reason.lastStanding", ("{0}만 끝까지 남았어요", "{0} was the last one standing") },
        { "reason.othersGone", ("다른 쪽이 모두 기권하거나 나갔어요", "Everyone else conceded or left") },
        { "reason.hostLeft", ("호스트가 게임을 나가 대전이 끝났어요", "The host left, so the match is over") },
        { "result.over", ("대전 종료", "Match over") },
        { "result.stampOver", ("끝", "End") },
        { "stats.kills", ("킬", "Kills") },
        { "stats.nongae", ("논개", "Nongae") },
        { "stats.suicides", ("자살", "Suicides") },
        { "stats.teamKills", ("팀킬", "Team kills") },
        { "kill.nongae", ("논개", "Nongae") },
        { "kill.suicide", ("자살", "Suicide") },
        { "kill.teamKill", ("팀킬", "Team kill") },
        { "stats.shots", ("튕긴 횟수", "Shots") },
        { "stats.time", ("경기 시간 {0}", "Match time {0}") },
        { "stats.rating", ("레이팅", "Rating") },
        { "series.score", ("연속 전적  {0} {1} : {2} {3}", "Series  {0} {1} : {2} {3}") },
        { "series.draws", (" · 무 {0}", " · {0} drawn") },
        { "series.panel", ("{0} · {1}승", "{0} · {1}W") },
        { "series.multi", ("연속 전적  {0}", "Series  {0}") },
        { "series.side", ("{0} {1}", "{0} {1}") },
        { "rematch.request", ("재대결", "Rematch") },
        { "rematch.accept", ("재대결 수락", "Accept rematch") },
        { "rematch.waiting", ("상대 기다리는 중…", "Waiting…") },
        { "rematch.opponentWants", ("상대가 재대결을 원해요", "Your opponent wants a rematch") },
        { "rematch.opponentLobby", ("상대가 로비로 돌아갔어요", "Your opponent went back to the lobby") },
        { "rematch.opponentLeft", ("상대가 나갔어요", "Your opponent left") },
        { "rematch.count", ("재대결 {0}/{1}명", "Rematch {0}/{1}") },
        { "rematch.othersGone", ("다른 플레이어가 모두 나갔어요", "Everyone else has left") },
        { "match.teams", ("팀전", "Teams") },
        { "lobby.addBot", ("봇 추가", "Add bot") },
        { "lobby.bot", ("봇", "Bot") },
        { "team.number", ("{0}팀", "Team {0}") },
        { "level.AIEasy", ("쉬움", "Easy") },
        { "level.AINormal", ("보통", "Normal") },
        { "level.AIHard", ("어려움", "Hard") },
        { "lobby.status.teams", ("팀전은 두 명씩 두 팀이어야 해요", "Teams need two of two") },
        { "rematch.teams", ("팀전은 네 명이 모두 있어야 해요", "Teams need all four players") },
        { "bot.AIEasy", ("봇 (쉬움)", "Bot (easy)") },
        { "bot.AINormal", ("봇 (보통)", "Bot (normal)") },
        { "bot.AIHard", ("봇 (어려움)", "Bot (hard)") },
        { "teams.twoByTwo", ("2:2 (마주 보는 자리끼리)", "2 v 2 (across from each other)") },
        { "team.tag", ("{0} · {1}팀", "{0} · team {1}") },
        { "win.team", ("{0}팀 승리", "Team {0} wins") },
        { "reason.teamStanding", ("{0}팀만 끝까지 남았어요", "Only team {0} is left") },
        { "ranked.series", ("랭크전 {0}판째 · {1} {2} : {3} {4}", "Ranked game {0} · {1} {2} : {3} {4}") },
        { "ranked.next", ("다음 판 {0}초 뒤 · 나가면 시리즈 패배", "Next game in {0}s · leaving loses the series") },
        { "ranked.nextButton", ("다음 판", "Next game") },
        { "ranked.over", ("랭크전 끝", "Ranked match over") },
        { "ranked.win", ("시리즈 승리", "Series won") },
        { "ranked.lose", ("시리즈 패배", "Series lost") },
        { "ranked.draw", ("시리즈 무승부", "Series drawn") },
        { "ranked.left", ("상대가 나가서 시리즈를 이겼어요", "The opponent left: the series is yours") },
        { "rematch.boardPlayers", ("이 판은 {0}명이 할 수 없어요 · 로비에서 판을 바꾸세요", "This board isn't for {0} players · change it in the lobby") },
        { "gameover.lobby", ("로비로", "Lobby") },

        { "menu.title", ("알까기", "Alkkagi") },
        { "menu.local", ("로컬 대전", "Local match") },
        { "menu.localSub", ("한 PC에서 2–4인, 자리마다 사람이나 AI", "2 to 4 at one PC, each a person or the AI") },
        { "opponent.Human", ("사람", "Player") },
        { "opponent.AIEasy", ("AI 쉬움", "AI easy") },
        { "opponent.AINormal", ("AI 보통", "AI normal") },
        { "opponent.AIHard", ("AI 어려움", "AI hard") },
        { "menu.online", ("온라인 대전", "Online match") },
        { "menu.onlineSub", ("Steam 친구나 공개 로비에서", "With a friend or a public lobby") },
        { "menu.settings", ("설정", "Settings") },
        { "menu.ranking", ("랭킹", "Rankings") },
        { "menu.quit", ("종료", "Quit") },
        { "menu.steamUser", ("Steam · {0} · 레이팅 {1}", "Steam · {0} · Rating {1}") },

        // The rankings card (LeaderboardPanel): the Steam leaderboard of ratings.
        { "rank.title", ("랭킹", "Rankings") },
        { "rank.scope.top", ("전체", "Top") },
        { "rank.scope.around", ("내 주변", "Around me") },
        { "rank.scope.friends", ("친구", "Friends") },
        { "rank.place", ("순위", "Rank") },
        { "rank.name", ("이름", "Name") },
        { "rank.rating", ("레이팅", "Rating") },
        { "rank.recordHeader", ("전적", "Record") },
        { "rank.record", ("{0}승 {1}패", "{0}W {1}L") },
        { "rank.recordDraws", ("{0}승 {1}패 {2}무", "{0}W {1}L {2}D") },
        { "rank.summary", ("내 레이팅 {0} · {1}", "Your rating {0} · {1}") },
        { "rank.summaryPlace", (" · {0}위", " · #{0}") },
        { "rank.noGames", ("아직 랭크전 기록이 없어요", "No ranked matches yet") },
        { "rank.loading", ("불러오는 중…", "Loading…") },
        { "rank.empty", ("아직 기록이 없어요", "No one here yet") },
        { "rank.offline", ("Steam에 연결되어 있지 않아요", "Not connected to Steam") },
        { "rank.failed", ("순위를 불러오지 못했어요", "Couldn't load the rankings") },
        { "rank.caption", ("온라인 랭크전 결과로 오르내려요 · 시작 레이팅 1000", "Online ranked matches move it · everyone starts at 1000") },

        { "settings.title", ("설정", "Settings") },
        { "settings.language", ("언어", "Language") },
        { "settings.close", ("닫기", "Close") },
        { "settings.sound", ("소리", "Sound") },
        { "settings.masterVolume", ("전체 음량", "Master volume") },
        { "settings.interfaceVolume", ("인터페이스 음량", "Interface volume") },
        { "settings.musicVolume", ("음악 음량", "Music volume") },
        { "settings.effectsVolume", ("효과음 음량", "Effects volume") },
        { "settings.controls", ("조작", "Controls") },
        { "settings.reset", ("기본값으로", "Reset") },
        { "settings.janggiLetters", ("장기말 글자", "Janggi letters") },
        { "settings.general", ("일반", "General") },
        { "settings.display", ("화면", "Display") },
        { "settings.windowMode", ("화면 모드", "Window mode") },
        { "settings.fullscreen", ("전체 화면", "Fullscreen") },
        { "settings.windowed", ("창 모드", "Windowed") },
        { "settings.windowSize", ("창 크기", "Window size") },
        { "settings.sizeValue", ("{0} × {1}", "{0} × {1}") },
        { "settings.hangul", ("한글", "Hangul") },
        { "settings.hanja", ("한자", "Hanja") },
        { "bind.CameraView", ("시점 전환 (누르고 있기)", "Camera view (hold)") },
        { "bind.CancelAim", ("조준 취소", "Cancel aim") },
        { "bind.PanView", ("시점 이동 (누르고 끌기)", "Pan view (hold and drag)") },
        { "bind.ResetView", ("시점 초기화", "Reset view") },
        { "bind.FineAim", ("미세 조준 (당기며 누르고 있기)", "Fine aim (hold while pulling)") },
        { "bind.press", ("키를 누르세요 · Esc 취소", "Press a key · Esc cancels") },
        { "key.mouseRight", ("마우스 오른쪽", "Right mouse") },
        { "key.mouseMiddle", ("마우스 가운데", "Middle mouse") },
        { "key.mouseN", ("마우스 {0}", "Mouse {0}") },
        { "key.left", ("왼쪽 {0}", "Left {0}") },
        { "key.right", ("오른쪽 {0}", "Right {0}") },
        { "key.space", ("스페이스", "Space") },
        { "option.on", ("켜기", "On") },
        { "option.off", ("끄기", "Off") },
        { "option.stones", ("{0}개", "{0}") },
        { "option.players", ("최대 {0}명", "Up to {0}") },
        { "option.seconds", ("{0}초", "{0}s") },
        { "option.noLimit", ("제한 없음", "None") },
        { "option.health", ("{0}", "{0}") },
        { "option.rounds", ("{0}라운드", "{0} rounds") },

        // Match rules (MatchSettings.Defs), shown in the lobby and the local setup screen.
        { "match.title", ("대전 규칙", "Match rules") },
        { "match.mode", ("모드", "Mode") },
        // Normal (and Item, later) are rated, with the balance rules fixed; Custom opens them all.
        { "mode.Normal", ("일반전", "Normal") },
        { "mode.Item", ("아이템전", "Items") },
        { "mode.Custom", ("커스텀", "Custom") },
        { "mode.Ranked", ("랭크전", "Ranked") },
        { "match.board", ("판", "Board") },
        { "match.pieces", ("알", "Pieces") },
        { "board.Go", ("바둑판", "Go board") },
        { "board.Janggi", ("장기판 (경첩)", "Janggi (hinged)") },
        { "board.Chess", ("체스판", "Chess board") },
        { "board.Hexagon", ("육각판", "Hexagon board") },
        { "board.Cross", ("십자판", "Cross board") },
        { "pieces.GoStones", ("바둑알", "Go stones") },
        { "pieces.JanggiPieces", ("장기말", "Janggi pieces") },
        { "pieces.ChessPieces", ("체스말", "Chess pieces") },
        { "pieces.GonggiStones", ("공기알", "Gonggi stones") },
        // A chess piece's letter in the kill feed: the notation's, in both languages.
        { "chess.King", ("K", "K") },
        { "chess.Queen", ("Q", "Q") },
        { "chess.Rook", ("R", "R") },
        { "chess.Bishop", ("B", "B") },
        { "chess.Knight", ("N", "N") },
        { "chess.Pawn", ("P", "P") },
        // Rolled by the host for each match.
        { "board.Random", ("랜덤", "Random") },
        { "pieces.Random", ("랜덤", "Random") },
        { "match.aimGuide", ("조준 가이드", "Aim guide") },
        { "match.blackStones", ("흑·초 알 개수", "Black/Cho pieces") },
        { "match.whiteStones", ("백·한 알 개수", "White/Han pieces") },
        { "match.blueStones", ("청 알 개수", "Blue pieces") },
        { "match.redStones", ("적·흑 알 개수", "Red/Black pieces") },
        { "match.stones", ("알 개수", "Pieces") },
        { "match.stonesOf", ("{0} 알 개수", "{0} pieces") },
        { "rules.group.game", ("경기", "Match") },
        { "rules.group.players", ("인원", "Players") },
        { "rules.group.board", ("판과 알", "Board and pieces") },
        { "rules.group.placement", ("배치", "Placement") },
        { "rules.group.end", ("시간과 끝내기", "Time and ending") },
        { "rules.group.assist", ("보조", "Assist") },
        { "rules.perSide", ("진영별로", "Per side") },
        { "rules.allSame", ("모두 같게", "All the same") },
        { "rules.perSideValue", ("진영별", "Per side") },
        { "rules.autoChanged", ("함께 바뀜 · {0}", "Changed to fit · {0}") },
        { "rules.change", ("{0} {1} → {2}", "{0} {1} → {2}") },
        { "rules.andMore", (" 외 {0}개", " and {0} more") },
        { "menu.practice", ("연습", "Practice") },
        { "hud.double", ("{0} 더블! 한 번에 2개", "{0}: double! Two in one shot") },
        { "hud.triple", ("{0} 트리플! 한 번에 3개", "{0}: triple! Three in one shot") },
        { "hud.multi", ("{0} 한 번에 {1}개!", "{0}: {1} in one shot!") },
        { "settings.screenShake", ("화면 흔들림", "Screen shake") },
        { "practice.offerTitle", ("처음이신가요?", "New to alkkagi?") },
        { "practice.offerBody", ("2분이면 기본 조작을 익힐 수 있어요.\n메인 메뉴의 '연습'에서 언제든 다시 할 수 있어요.", "Two minutes to learn the controls.\nPractice stays on the main menu for whenever you want it.") },
        { "practice.later", ("나중에", "Later") },
        { "practice.start", ("연습하기", "Practice") },
        { "tutorial.step", ("연습 {0}/{1}", "Practice {0}/{1}") },
        { "tutorial.skip", ("건너뛰기", "Skip") },
        { "tutorial.pull", ("당기기", "Pull") },
        { "tutorial.pullBody", ("흑 알을 누른 채 뒤로 끌어 보세요. 끈 반대쪽으로 날아가요.", "Press one of your black stones and drag back. It flies the other way.") },
        { "tutorial.release", ("놓기", "Let go") },
        { "tutorial.releaseBody", ("버튼을 놓으면 튕겨 나가요. 멀리 당길수록 세게 나가요.", "Let go of the button to flick it. The further you pull, the harder it goes.") },
        { "tutorial.knock", ("떨어뜨리기", "Knock off") },
        { "tutorial.knockBody", ("백 알을 맞혀 판 밖으로 떨어뜨려 보세요. 그동안 백은 쉬어요.", "Hit a white stone off the board. White sits out meanwhile.") },
        { "tutorial.fine", ("미세 조준", "Fine aim") },
        { "tutorial.fineBody", ("당기는 동안 {0} 누르고 있기. 당김이 4배 천천히 따라와서 세밀하게 맞출 수 있어요.", "Hold {0} while you pull: the pull follows four times slower, for a finer aim.") },
        { "tutorial.view", ("시점", "View") },
        { "tutorial.viewBody", ("판 옮기기: {0} 누른 채 끌기 · 확대·축소: 휠. 판을 옮겨 보세요.", "Move the board: hold {0} and drag. Zoom: the wheel. Move the board now.") },
        { "tutorial.viewBack", ("이제 되돌려 보세요: {0}, 또는 오른쪽 아래 '시점 초기화'.", "Now put it back: {0}, or Reset view at the bottom right.") },
        { "tutorial.play", ("한 판", "A real game") },
        { "tutorial.playBody", ("이제 백도 둬요. 백 알을 모두 떨어뜨리면 이기고, 내 알이 다 떨어지면 져요.", "White plays now. Knock all its stones off to win; lose all yours and you lose.") },
        { "pause.rules", ("이번 판 규칙", "This match's rules") },
        { "rules.title", ("이번 판 규칙", "This match's rules") },
        { "rules.close", ("닫기", "Close") },
        { "rules.ranked", ("랭크전 · 3판 2선승 · 레이팅에 반영", "Ranked · best of three · rated") },
        { "rules.win", ("상대 알을 모두 판 밖으로 떨어뜨리면 이겨요.", "Knock all the other side's pieces off the board to win.") },
        { "rules.winMulti", ("알이 마지막까지 남은 진영이 이겨요.", "The last side with pieces on the board wins.") },
        { "rules.winTeams", ("두 명씩 두 팀, 팀원은 마주 앉아요. 상대 팀의 알을 모두 떨어뜨리면 이겨요.", "Two teams of two, teammates across from each other. Knock all the other team's pieces off to win.") },
        { "rules.healthPiece", ("체력전 A: 알마다 체력 {0}. 부딪히면 깎이고(톡 1 ~ 정면 풀파워 {1}), 다 되면 그 알은 깨져요.", "Health A: each piece has {0}. Knocks cost from 1 for a tap to {1} for a full-power hit; a piece with none left breaks.") },
        { "rules.healthSide", ("체력전 B: 진영 체력 {0}. 부딪히면 깎이고(톡 1 ~ 정면 풀파워 {1}), 알이 떨어지면 {2}. 다 되면 탈락이에요.", "Health B: each side has {0}. Knocks cost 1 up to {1}, a piece off the board {2}; with none left, the side is out.") },
        { "rules.walls", ("사방에 벽이 있어 알이 떨어지지 않아요. 벽에 부딪혀도 체력이 깎여요.", "Walls all round: nothing falls off, and hitting a wall hurts too.") },
        { "rules.board", ("{0} · {1} · 진영마다 {2}", "{0} · {1} · {2} a side") },
        { "rules.boardBySide", ("{0} · {1} · 알 {2}", "{0} · {1} · pieces {2}") },
        { "rules.placement", ("알은 직접 놓고 시작해요 ({0}).", "Each side places its own pieces first ({0}).") },
        { "rules.turn", ("한 턴에 {0}초. 시간이 다 되면 차례가 넘어가요.", "{0} seconds a turn; run out and the turn passes.") },
        { "rules.turnFree", ("턴 시간 제한은 없어요.", "No turn clock.") },
        { "rules.zone", ("3라운드 동안 아무것도 안 떨어지면 판 가장자리가 무너지기 시작해요. 1턴 전에 예고해요.", "Three rounds with nothing knocked off and the edge starts to crumble, announced a turn ahead.") },
        { "rules.rounds", ("{0}라운드가 끝나면 남은 알(체력전은 체력)이 많은 쪽이 이겨요.", "After {0} rounds, the side with the most left (health, in a battle of health) wins.") },
        { "rules.bothOut", ("마지막 알끼리 함께 떨어지면: {0}", "If the last pieces go off together: {0}") },
        { "rules.noGuide", ("조준 가이드는 없어요.", "No aim guide.") },
        { "match.seats", ("인원", "Players") },
        { "match.spawn", ("알 배치", "Setup") },
        { "match.placementStyle", ("배치 방식", "Placement") },
        { "match.placementTime", ("배치 시간", "Setup time") },
        { "match.turnTime", ("턴 제한시간", "Turn timer") },
        { "match.bothOut", ("동시 소진 시", "If both run out") },
        { "match.variant", ("게임 방식", "Game") },
        { "variant.Classic", ("클래식", "Classic") },
        { "variant.Health", ("체력전", "Health battle") },
        { "match.healthRule", ("체력 규칙", "Health rule") },
        { "healthRule.PerPiece", ("A · 알마다 체력", "A · Each piece its own") },
        { "healthRule.Side", ("B · 진영 체력", "B · Shared by the side") },
        { "match.pieceHealth", ("알 체력", "Piece health") },
        { "match.sideHealth", ("진영 체력", "Side health") },
        { "match.barrier", ("배리어 (사방 벽)", "Walls round the board") },
        { "match.zone", ("자기장", "Crumbling edge") },
        { "match.roundLimit", ("라운드 제한", "Round limit") },
        { "spawn.preset", ("기본 배치", "Preset") },
        { "spawn.placement", ("직접 배치", "Place freely") },
        { "placement.styleHidden", ("동시 · 비공개", "Hidden") },
        { "placement.styleLive", ("동시 · 공개", "Open") },
        { "placement.styleAlternating", ("번갈아 한 개씩", "Take turns") },
        { "bothOut.ShooterLoses", ("쏜 쪽 패배", "Shooter loses") },
        { "bothOut.ShooterWins", ("쏜 쪽 승리", "Shooter wins") },
        { "bothOut.Draw", ("무승부", "Draw") },
        { "setup.start", ("시작", "Start") },
        { "setup.cancel", ("취소", "Cancel") },

        { "lobby.title", ("온라인 대전", "Online match") },
        { "lobby.create", ("로비 만들기", "Create lobby") },
        { "lobby.createSub", ("호스트로 친구 초대", "Host, invite friends") },
        { "lobby.joinLabel", ("로비 코드로 참가", "Join with a lobby code") },
        { "lobby.codePlaceholder", ("로비 코드 입력", "Enter lobby code") },
        { "lobby.join", ("참가", "Join") },
        { "lobby.back", ("뒤로", "Back") },
        { "lobby.code", ("로비 코드", "Lobby code") },
        { "lobby.copy", ("복사", "Copy") },
        { "lobby.copied", ("복사됨", "Copied") },
        { "lobby.invite", ("Steam 친구 초대", "Invite a Steam friend") },
        { "lobby.emptySlot", ("빈 자리", "Open slot") },
        { "lobby.host", ("호스트", "Host") },
        { "lobby.guest", ("게스트", "Guest") },
        { "lobby.leave", ("나가기", "Leave") },
        { "lobby.quick", ("빠른 대전", "Quick match") },
        { "lobby.quickSub", ("일반전 바로 참가", "Join a Normal match") },
        { "lobby.ranked", ("랭크전", "Ranked") },
        { "lobby.rankedSub", ("1:1 · 3판 2선승", "1 on 1 · best of 3") },
        { "lobby.browser", ("공개 로비", "Public lobbies") },
        { "lobby.refresh", ("새로고침", "Refresh") },
        { "lobby.browserEmpty", ("열린 공개 로비가 없어요", "No open public lobbies") },
        { "lobby.browserSearching", ("찾는 중…", "Searching…") },
        { "lobby.browserCaption", ("같은 버전의 게임에서 만든 로비만 보여요", "Only lobbies on this game version show up") },
        { "lobby.rowRules", ("{0} · {1} · {2} · {3}/{4}명", "{0} · {1} · {2} · {3}/{4}") },
        { "lobby.visibility", ("공개 범위", "Who can join") },
        { "lobby.vis.public", ("공개", "Public") },
        { "lobby.vis.friends", ("친구", "Friends") },
        { "lobby.vis.private", ("비공개", "Private") },
        { "lobby.kick", ("내보내기", "Remove") },
        { "lobby.rulesNormal", ("일반전 · 레이팅 미반영 · 흐린 규칙은 고정", "Normal · not rated · dimmed rules are fixed") },
        { "lobby.rulesRanked", ("랭크전 · 3판 2선승 · 레이팅 반영 · 규칙 고정", "Ranked · best of 3 · rated · rules fixed") },
        { "lobby.rulesCustom", ("커스텀 · 모든 규칙 변경 가능 · 레이팅 미반영", "Custom · every rule open · not rated") },
        { "lobby.start", ("매치 시작", "Start match") },
        { "lobby.status.noSteam", ("Steam에 연결할 수 없어요", "Can't reach Steam") },
        { "lobby.status.idle", ("로비를 만들거나 참가하세요", "Create or join a lobby") },
        { "lobby.status.creating", ("로비 만드는 중…", "Creating lobby…") },
        { "lobby.status.joining", ("참가하는 중…", "Joining…") },
        { "lobby.status.waitingOpponent", ("상대 기다리는 중", "Waiting for an opponent") },
        { "lobby.status.rankedSearching", ("랭크전 상대를 찾는 중", "Looking for a ranked opponent") },
        { "lobby.status.rankedStarting", ("상대를 찾았어요 · 곧 시작해요", "Opponent found · starting") },
        { "lobby.status.rankedOver", ("랭크전이 끝났어요", "The ranked match is over") },
        { "lobby.status.boardPlayers", ("이 판은 {0}명이 할 수 없어요 · 판을 바꾸거나 봇을 넣으세요", "This board isn't for {0} players · change it or add a bot") },
        { "lobby.status.waitingHost", ("호스트의 시작을 기다리는 중", "Waiting for the host") },
        { "lobby.status.ready", ("시작할 수 있어요", "Ready to start") },
        { "lobby.status.readyCount", ("{0}/{1}명 · 시작할 수 있어요", "{0}/{1} players · ready to start") },
        { "lobby.status.badCode", ("올바른 로비 코드를 입력하세요", "Enter a valid lobby code") },
        { "lobby.status.failed", ("로비에 들어가지 못했어요", "Couldn't enter the lobby") },
        { "lobby.status.searching", ("공개 로비 찾는 중…", "Looking for a public lobby…") },
        { "lobby.status.version", ("게임 버전이 달라 참가할 수 없어요", "That lobby runs a different game version") },
        { "lobby.status.kicked", ("호스트가 로비에서 내보냈어요", "The host removed you from the lobby") },
        { "lobby.status.blocked", ("차단한 플레이어가 있어 로비에서 나왔어요", "Left: a player you blocked is in that lobby") },
        { "lobby.block", ("차단", "Block") },
        { "result.report", ("신고·차단", "Report / block") },
        { "report.title", ("신고·차단", "Report or block") },
        { "report.caption", ("차단한 플레이어와는 다시 만나지 않아요. 신고는 Steam 프로필에서 이어져요.", "You won't be matched with a blocked player again. Reports go on in their Steam profile.") },
        { "report.block", ("차단", "Block") },
        { "report.report", ("신고", "Report") },
        { "report.blocked", ("차단함", "Blocked") },
        { "report.close", ("닫기", "Close") },
        { "settings.online", ("온라인", "Online") },
        { "settings.blocked", ("차단한 플레이어 {0}명", "{0} blocked") },
        { "settings.unblockAll", ("모두 해제", "Unblock all") },
    };
}
